Repository RIOT-OS/Release-Specs, pull requests merged in 2020-07, with the labels that each got.

#157 08-interop: deprecate 9-10
  08-interop/08-interop.md
  README.md
  REPLACED.md
Labels: cleanup

#166 task8.3: adapt testing procedures for current RIOT
  08-interop/08-interop.md
Labels: enhancement

#155 testutils: Automated testing environment for release tests using pytest
  .github/workflows/self-test.yml
  .gitignore
  README.md
  conftest.py
  setup.cfg
  testutils/.coveragerc
  testutils/__init__.py
  testutils/asyncio.py
  testutils/iotlab.py
  testutils/native.py
  testutils/pytest.py
  testutils/shell.py
  testutils/tests/__init__.py
  testutils/tests/test_iotlab.py
  testutils/tests/test_native.py
  testutils/tests/test_pytest.py
  testutils/tests/test_shell.py
  tox.ini
Labels: enhancement

#169 gh-actions: remove test branch from self-test
  .github/workflows/self-test.yml
Labels: cleanup

#170 README.md: add note how to run specific tests
  README.md
Labels: enhancement

#161 04-single-hop-6lowpan-icmp: initial import of automated tests
  04-single-hop-6lowpan-icmp/test_spec04.py
Labels: enhancement

#171 pytest: fail test on flash fail
  conftest.py
Labels: bug, enhancement

#162 05-single-hop-route: initial import of automated tests
  05-single-hop-route/test_spec05.py
Labels: enhancement

#160 03-single-hop-ipv6-icmp: initial import of automated tests
  03-single-hop-ipv6-icmp/test_spec03.py
Labels: enhancement

#163 06-single-hop-udp: initial import of automated tests
  06-single-hop-udp/test_spec06.py
Labels: enhancement

#159 08-interop: initial import of automated tests
  08-interop/test_spec08.py
Labels: enhancement

#167 10-icmpv6-error: initial import of automated tests
  10-icmpv6-error/test_spec10.py
  conftest.py
Labels: enhancement

#158 07-multi-hop: port automated tests to pytest
  07-multi-hop/IOTLABHelper.py
  07-multi-hop/task01.py
  07-multi-hop/task02.py
  07-multi-hop/task03.py
  07-multi-hop/task04.py
  07-multi-hop/test_spec07.py
  testutils/shell.py
  testutils/tests/test_shell.py
Labels: enhancement

#168 09-coap: port to pytest-based framework
  09-coap/test_spec09.py
  tox.ini
Labels: enhancement, help wanted

#177 README: some improvements
  README.md
  requirements.txt
  tox.ini
Labels: enhancement

#176 07-multi-hop: some clean-up for the automated tests
  07-multi-hop/test_spec07.py
Labels: cleanup

#179 tox: activate flake8 and pylint on default runs
  setup.cfg
  tox.ini
Labels: enhancement
