Repository RIOT-OS/Release-Specs, pull requests merged in 2020-08, with the labels that each got.

#180 03-single-hop-ipv6-icmp/task04: stop pingers after force-ping
  03-single-hop-ipv6-icmp/test_spec03.py
Labels: bug

#184 09-coap/task02&05: shutdown server properly
  09-coap/test_spec09.py
Labels: bug

#183 04-single-hop-6lowpan-icmp/task04: xfail pktbuf on pinged node
  04-single-hop-6lowpan-icmp/test_spec04.py
Labels: bug

#178 pytest: add workaround to add USEMODULE with BUILD_IN_DOCKER
  conftest.py
  tox.ini
Labels: enhancement

#173 testutils: mark tests in RC tracking issue and comment on status
  conftest.py
  requirements.txt
  testutils/github.py
  testutils/tests/test_github.py
  tox.ini
Labels: enhancement

#182 pytest: add capability to log nodes to file
  README.md
  conftest.py
  testutils/pytest.py
Labels: enhancement

#185 08-interop: add test for WiFi <-> DHCPv6 router
  08-interop/README.md
Labels: enhancement

#187 tox: remove unneeded gh-actions env
  tox.ini
Labels: cleanup

#181 04-single-hop-6lowpan-icmp/task04: reconnect terminal after long test
  04-single-hop-6lowpan-icmp/test_spec04.py
Labels: bug

#190 09-coap/task01: use upstream CordEp ShellInteraction
  09-coap/test_spec09.py
Labels: enhancement

#191 09-coap/task01: fix typo
  09-coap/test_spec09.py
Labels: bug
